### PR TITLE
Update istanbul@0.3.17

### PR DESCRIPTION
**Pull request by AndreMommert**

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks, but unless this is actually solving some kind of issue, we really don't take patches for dev dependencies. What issue does updating solve?

**Comment by AndreMommert** [comment]
v0.3.17	Upgrade esprima, get correct for-of support

**Comment by dougwilson** [comment]
Right, but does that solve an issue with this module? I don't think we use for of, correct?

**Comment by dougwilson** [comment]
In the future, please be courteous and restrain from useless PRs :)

**Pull request closed without merging**
